### PR TITLE
Fix missing axios

### PR DESCRIPTION
**Pull request by pbek**
`yarn run start` did fail for me

### CODE REVIEW

**Comment by pbek** [comment]
Thank you for helping me out with implementing a permanent token generation for https://github.com/muesli/beehive with your source code!

**Review by Bnjis — APPROVED** [review]
Oh right thanks. 

Sorry for the delay, i have lot of work :)

**Comment by pbek** [comment]
I didn't even remember this PR any more. 😆

**Comment by Bnjis** [comment]
Hahahha :P

**Pull request merged**
